//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Mon Sep  9 18:11:09 CEST 2024
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1 const
// response_get                   O    32
// RDY_response_get               O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I    32
// EN_request_put                 I     1
// EN_response_get                I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCICComplexDecimationFilter_25_4_1_19_16_16(CLK,
						    RST_N,

						    request_put,
						    EN_request_put,
						    RDY_request_put,

						    EN_response_get,
						    response_get,
						    RDY_response_get);
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [31 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [31 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [31 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // inlined wires
  wire [69 : 0] ifc_wr_x$wget;

  // register ifc_count
  reg [4 : 0] ifc_count;
  wire [4 : 0] ifc_count$D_IN;
  wire ifc_count$EN;

  // register ifc_ddly_0_0
  reg [69 : 0] ifc_ddly_0_0;
  wire [69 : 0] ifc_ddly_0_0$D_IN;
  wire ifc_ddly_0_0$EN;

  // register ifc_ddly_1_0
  reg [69 : 0] ifc_ddly_1_0;
  wire [69 : 0] ifc_ddly_1_0$D_IN;
  wire ifc_ddly_1_0$EN;

  // register ifc_ddly_2_0
  reg [69 : 0] ifc_ddly_2_0;
  wire [69 : 0] ifc_ddly_2_0$D_IN;
  wire ifc_ddly_2_0$EN;

  // register ifc_ddly_3_0
  reg [69 : 0] ifc_ddly_3_0;
  wire [69 : 0] ifc_ddly_3_0$D_IN;
  wire ifc_ddly_3_0$EN;

  // register ifc_dstg_0
  reg [69 : 0] ifc_dstg_0;
  wire [69 : 0] ifc_dstg_0$D_IN;
  wire ifc_dstg_0$EN;

  // register ifc_dstg_1
  reg [69 : 0] ifc_dstg_1;
  wire [69 : 0] ifc_dstg_1$D_IN;
  wire ifc_dstg_1$EN;

  // register ifc_dstg_2
  reg [69 : 0] ifc_dstg_2;
  wire [69 : 0] ifc_dstg_2$D_IN;
  wire ifc_dstg_2$EN;

  // register ifc_dstg_3
  reg [69 : 0] ifc_dstg_3;
  wire [69 : 0] ifc_dstg_3$D_IN;
  wire ifc_dstg_3$EN;

  // register ifc_istg_0
  reg [69 : 0] ifc_istg_0;
  wire [69 : 0] ifc_istg_0$D_IN;
  wire ifc_istg_0$EN;

  // register ifc_istg_1
  reg [69 : 0] ifc_istg_1;
  wire [69 : 0] ifc_istg_1$D_IN;
  wire ifc_istg_1$EN;

  // register ifc_istg_2
  reg [69 : 0] ifc_istg_2;
  wire [69 : 0] ifc_istg_2$D_IN;
  wire ifc_istg_2$EN;

  // register ifc_istg_3
  reg [69 : 0] ifc_istg_3;
  wire [69 : 0] ifc_istg_3$D_IN;
  wire ifc_istg_3$EN;

  // remaining internal signals
  wire [34 : 0] x__h3549, x__h3598;
  wire [15 : 0] request_put_BITS_15_TO_0__q2, request_put_BITS_31_TO_16__q1;
  wire [4 : 0] x__h3458;

  // action method request_put
  assign RDY_request_put = 1'd1 ;

  // actionvalue method response_get
  assign response_get = { x__h3549[34:19], x__h3598[34:19] } ;
  assign RDY_response_get = ifc_count == 5'd24 ;

  // inlined wires
  assign ifc_wr_x$wget =
	     { { {19{request_put_BITS_31_TO_16__q1[15]}},
		 request_put_BITS_31_TO_16__q1 },
	       { {19{request_put_BITS_15_TO_0__q2[15]}},
		 request_put_BITS_15_TO_0__q2 } } ;

  // register ifc_count
  assign ifc_count$D_IN = (ifc_count == 5'd24) ? 5'd0 : x__h3458 ;
  assign ifc_count$EN = 1'd1 ;

  // register ifc_ddly_0_0
  assign ifc_ddly_0_0$D_IN = ifc_istg_3 ;
  assign ifc_ddly_0_0$EN = ifc_count == 5'd24 ;

  // register ifc_ddly_1_0
  assign ifc_ddly_1_0$D_IN = ifc_dstg_0 ;
  assign ifc_ddly_1_0$EN = ifc_count == 5'd24 ;

  // register ifc_ddly_2_0
  assign ifc_ddly_2_0$D_IN = ifc_dstg_1 ;
  assign ifc_ddly_2_0$EN = ifc_count == 5'd24 ;

  // register ifc_ddly_3_0
  assign ifc_ddly_3_0$D_IN = ifc_dstg_2 ;
  assign ifc_ddly_3_0$EN = ifc_count == 5'd24 ;

  // register ifc_dstg_0
  assign ifc_dstg_0$D_IN =
	     { ifc_istg_3[69:35] - ifc_ddly_0_0[69:35],
	       ifc_istg_3[34:0] - ifc_ddly_0_0[34:0] } ;
  assign ifc_dstg_0$EN = ifc_count == 5'd24 ;

  // register ifc_dstg_1
  assign ifc_dstg_1$D_IN =
	     { ifc_dstg_0[69:35] - ifc_ddly_1_0[69:35],
	       ifc_dstg_0[34:0] - ifc_ddly_1_0[34:0] } ;
  assign ifc_dstg_1$EN = ifc_count == 5'd24 ;

  // register ifc_dstg_2
  assign ifc_dstg_2$D_IN =
	     { ifc_dstg_1[69:35] - ifc_ddly_2_0[69:35],
	       ifc_dstg_1[34:0] - ifc_ddly_2_0[34:0] } ;
  assign ifc_dstg_2$EN = ifc_count == 5'd24 ;

  // register ifc_dstg_3
  assign ifc_dstg_3$D_IN =
	     { ifc_dstg_2[69:35] - ifc_ddly_3_0[69:35],
	       ifc_dstg_2[34:0] - ifc_ddly_3_0[34:0] } ;
  assign ifc_dstg_3$EN = ifc_count == 5'd24 ;

  // register ifc_istg_0
  assign ifc_istg_0$D_IN =
	     { ifc_istg_0[69:35] + ifc_wr_x$wget[69:35],
	       ifc_istg_0[34:0] + ifc_wr_x$wget[34:0] } ;
  assign ifc_istg_0$EN = EN_request_put ;

  // register ifc_istg_1
  assign ifc_istg_1$D_IN =
	     { ifc_istg_1[69:35] + ifc_istg_0[69:35],
	       ifc_istg_1[34:0] + ifc_istg_0[34:0] } ;
  assign ifc_istg_1$EN = EN_request_put ;

  // register ifc_istg_2
  assign ifc_istg_2$D_IN =
	     { ifc_istg_2[69:35] + ifc_istg_1[69:35],
	       ifc_istg_2[34:0] + ifc_istg_1[34:0] } ;
  assign ifc_istg_2$EN = EN_request_put ;

  // register ifc_istg_3
  assign ifc_istg_3$D_IN =
	     { ifc_istg_3[69:35] + ifc_istg_2[69:35],
	       ifc_istg_3[34:0] + ifc_istg_2[34:0] } ;
  assign ifc_istg_3$EN = EN_request_put ;

  // remaining internal signals
  assign request_put_BITS_15_TO_0__q2 = request_put[15:0] ;
  assign request_put_BITS_31_TO_16__q1 = request_put[31:16] ;
  assign x__h3458 = ifc_count + 5'd1 ;
  assign x__h3549 =
	     ifc_dstg_3[69:35] + (ifc_dstg_3[54] ? 35'd262144 : 35'd262143) ;
  assign x__h3598 =
	     ifc_dstg_3[34:0] + (ifc_dstg_3[19] ? 35'd262144 : 35'd262143) ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        ifc_count <= `BSV_ASSIGNMENT_DELAY 5'd0;
	ifc_ddly_0_0 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_ddly_1_0 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_ddly_2_0 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_ddly_3_0 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_dstg_0 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_dstg_1 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_dstg_2 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_dstg_3 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_istg_0 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_istg_1 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_istg_2 <= `BSV_ASSIGNMENT_DELAY 70'd0;
	ifc_istg_3 <= `BSV_ASSIGNMENT_DELAY 70'd0;
      end
    else
      begin
        if (ifc_count$EN) ifc_count <= `BSV_ASSIGNMENT_DELAY ifc_count$D_IN;
	if (ifc_ddly_0_0$EN)
	  ifc_ddly_0_0 <= `BSV_ASSIGNMENT_DELAY ifc_ddly_0_0$D_IN;
	if (ifc_ddly_1_0$EN)
	  ifc_ddly_1_0 <= `BSV_ASSIGNMENT_DELAY ifc_ddly_1_0$D_IN;
	if (ifc_ddly_2_0$EN)
	  ifc_ddly_2_0 <= `BSV_ASSIGNMENT_DELAY ifc_ddly_2_0$D_IN;
	if (ifc_ddly_3_0$EN)
	  ifc_ddly_3_0 <= `BSV_ASSIGNMENT_DELAY ifc_ddly_3_0$D_IN;
	if (ifc_dstg_0$EN)
	  ifc_dstg_0 <= `BSV_ASSIGNMENT_DELAY ifc_dstg_0$D_IN;
	if (ifc_dstg_1$EN)
	  ifc_dstg_1 <= `BSV_ASSIGNMENT_DELAY ifc_dstg_1$D_IN;
	if (ifc_dstg_2$EN)
	  ifc_dstg_2 <= `BSV_ASSIGNMENT_DELAY ifc_dstg_2$D_IN;
	if (ifc_dstg_3$EN)
	  ifc_dstg_3 <= `BSV_ASSIGNMENT_DELAY ifc_dstg_3$D_IN;
	if (ifc_istg_0$EN)
	  ifc_istg_0 <= `BSV_ASSIGNMENT_DELAY ifc_istg_0$D_IN;
	if (ifc_istg_1$EN)
	  ifc_istg_1 <= `BSV_ASSIGNMENT_DELAY ifc_istg_1$D_IN;
	if (ifc_istg_2$EN)
	  ifc_istg_2 <= `BSV_ASSIGNMENT_DELAY ifc_istg_2$D_IN;
	if (ifc_istg_3$EN)
	  ifc_istg_3 <= `BSV_ASSIGNMENT_DELAY ifc_istg_3$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    ifc_count = 5'h0A;
    ifc_ddly_0_0 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_ddly_1_0 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_ddly_2_0 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_ddly_3_0 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_dstg_0 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_dstg_1 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_dstg_2 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_dstg_3 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_istg_0 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_istg_1 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_istg_2 = 70'h2AAAAAAAAAAAAAAAAA;
    ifc_istg_3 = 70'h2AAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCICComplexDecimationFilter_25_4_1_19_16_16

